### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by gabrielle-barnes** [gabrielle-barnes/RendezView#1]
We want to first start with setting up a React project. This includes running the necessary code lines in the terminal and creating the basic files.

Specific Instructions can be found here:
[React JS Tutorial #1](https://www.youtube.com/watch?v=NJaKzLiqMD8&list=PLB4OYaYkKsG6Yd9SPQJNnl0c4HXV3J9Ae)

**Comment by KalifByrd** [comment]
This has been completed!
