### ISSUE TITLE
Multiple Pages

### ISSUE THREAD

**Issue by gabrielle-barnes** [gabrielle-barnes/RendezView#2]
We will need to create multiple pages for the application (start with 3). We can create a HomePage, a User Profile Page, and a Friend Profile Page. It might be best to use the Router function that React has.

Details on Router and how to create pages here:
[Multiple Pages](https://www.youtube.com/watch?v=qi32YwjoN2U&list=PLB4OYaYkKsG6Yd9SPQJNnl0c4HXV3J9Ae&index=7)

We can start with very simple pages, literally just saying "This is the HomePage", "This is the User Profile Page", and so on.

**Comment by KalifByrd** [comment]
I started working on this!
- I added all 3 pages files
- The pages say: This is the home page, This is the user profile page, and This is the friends profile page
Might need more things didn't finish the tutorial
